[build]
publish = "public"
command = "bundle && hugo"

[context.production.environment]
HUGO_VERSION = "0.46"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.46"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.46"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.46"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"


[[redirects]]
from = "/blog/sources/rhdevel/*"
to = "https://developers.redhat.com/blog/:splat"
status =  200

[[redirects]]
from = "/blog/sources/openshift/*"
to = "https://blog.openshift.com/:splat"
status = 200
